[build]
  command = "yarn build"
  publish = "_site/"

[[redirects]]
  from = "https://avocadotoast.netlify.com/*"
  to = "https://avocadotoast.live/:splat"
  status = 301
  force = true

[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/episodes/:placeholder/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
